# Generated by Django 4.0.2 on 2022-05-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_alter_sale_price_alter_sale_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
    ]
